services:
  fastapi_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  fastapi_template:
    image: fastapi_template
    entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - fastapi_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@fastapi_database:5432/app_db

volumes:
  pgdata:
